//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStockApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class approvisionnement
    {
        public int idApp { get; set; }
        public int idProduit { get; set; }
        public double qteProduit { get; set; }
        public System.DateTime dateApprovisionnement { get; set; }
    }
}
