//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStockApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int id { get; set; }
        public string libelle { get; set; }
        public string description { get; set; }
        public double quantite { get; set; }
        public Nullable<double> quantiteMin { get; set; }
        public double prix { get; set; }
        public int codeCat { get; set; }
    }
}
